import { useEffect, useState } from 'react'
import { BrowserRouter, Navigate, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { AlertTriangle, Bell, Check, ChevronRight, Compass, Home, Info, Map, Mountain, Phone, Plus, Shield, Siren, User, X } from 'lucide-react'
import './App.css'
import { AuthProvider } from './context/AuthContext'
import { useAuth } from './context/useAuth'
import { addContact, createSOS, deleteContact, getAlerts, getContacts, markAllAlertsRead } from './services/api'
import { getCurrentLocation } from './utils/locationService'
import { kitItems, safetySections } from './utils/safety'
import { riskColor, riskOrder } from './utils/risk'

function App() { return <AuthProvider><BrowserRouter><Routes><Route path="/login" element={<PublicOnly><AuthPage mode="login" /></PublicOnly>} /><Route path="/signup" element={<PublicOnly><AuthPage mode="signup" /></PublicOnly>} /><Route element={<ProtectedLayout />}><Route path="/*" element={<Shell />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes></BrowserRouter></AuthProvider> }
function PublicOnly({ children }) { const { user, loading } = useAuth(); if (loading) return <PageLoader text="Checking your session..." />; return user ? <Navigate to="/" replace /> : children }
function ProtectedLayout() { const { user, loading } = useAuth(); if (loading) return <PageLoader text="Connecting to Bhu Raksha..." />; if (!user) return <Navigate to="/login" replace />; return <Shell /> }
function Shell() { const [sosOpen, setSosOpen] = useState(false); return <div className="app"><Header /><main className="content"><Routes><Route path="/" element={<HomePage setSosOpen={setSosOpen} />} /><Route path="/alerts" element={<AlertsPage />} /><Route path="/alerts/:id" element={<AlertDetail />} /><Route path="/map" element={<MapPage />} /><Route path="/safety" element={<SafetyPage />} /><Route path="/profile" element={<ProfilePage />} /><Route path="/contacts" element={<ContactsPage />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></main><SOSButton onClick={() => setSosOpen(true)} /><BottomNav />{sosOpen && <SOSModal close={() => setSosOpen(false)} />}</div> }
function Header() { const { user } = useAuth(); const navigate = useNavigate(); return <header className="header"><div className="brand" onClick={() => navigate('/')}><span className="brand-mark"><Mountain size={19} /><Shield size={13} /></span><span><strong>BHU RAKSHA</strong><small>STAY ALERT. STAY SAFE.</small></span></div><div className="header-actions"><NavLink to="/alerts" className="header-icon"><Bell size={19} /></NavLink><button className="avatar" onClick={() => navigate('/profile')}>{user?.name?.slice(0, 1).toUpperCase()}</button></div></header> }
function BottomNav() { return <nav className="bottom-nav">{[[Home, '/', 'Home'], [Bell, '/alerts', 'Alerts'], [Map, '/map', 'Map'], [Shield, '/safety', 'Safety'], [User, '/profile', 'Profile']].map(([Icon, path, label]) => <NavLink end={path === '/'} to={path} key={path}><Icon size={19} /><span>{label}</span></NavLink>)}</nav> }
function HomePage({ setSosOpen }) { const { user } = useAuth(); const [alerts, setAlerts] = useState([]); useEffect(() => { getAlerts().then(({ alerts: rows }) => setAlerts(rows)).catch(() => setAlerts([])) }, []); const current = [...alerts].sort((a, b) => (riskOrder[b.riskLevel] || 0) - (riskOrder[a.riskLevel] || 0))[0]; const hour = new Date().getHours(); const greeting = hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening'; return <><div className="welcome"><div><span className="eyebrow">CITIZEN SAFETY CENTER</span><h1>{greeting}, {user.name.split(' ')[0]}</h1><p>Your calm, clear view of local risk.</p></div><button className="round-action" onClick={setSosOpen}><Siren size={18} /></button></div><section className="location-card"><Compass size={20} /><div><span>YOUR MONITORED AREA</span><strong>{user.district}, {user.state}</strong><small>Location based on your profile</small></div><ChevronRight size={17} /></section>{current ? <RiskCard alert={current} /> : <section className="clear-card"><div className="clear-icon"><Check size={24} /></div><div><span className="eyebrow">CURRENT RISK</span><h2>All clear</h2><p>No active landslide alerts for your monitored area.</p></div></section>}<section className="section-heading"><div><span className="eyebrow">BE READY</span><h2>Safety center</h2></div><NavLink to="/safety">View all <ChevronRight size={14} /></NavLink></section><div className="safety-preview"><Shield size={20} /><div><strong>Know what to do before risk rises</strong><p>Practical guidance and emergency kit.</p></div><NavLink to="/safety"><ChevronRight /></NavLink></div><section className="section-heading"><div><span className="eyebrow">YOUR SUPPORT</span><h2>Need help?</h2></div></section><div className="help-grid"><a href="tel:112"><Phone size={19} /><strong>Call 112</strong><small>Emergency services</small></a><NavLink to="/contacts"><User size={19} /><strong>Trusted contacts</strong><small>Manage your circle</small></NavLink></div></> }
function RiskCard({ alert }) { const navigate = useNavigate(); return <section className="risk-card" style={{ '--risk': riskColor(alert.riskLevel) }}><div className="risk-card-top"><span className="eyebrow">CURRENT RISK · {alert.state}</span><span className="risk-badge">{alert.riskLevel}</span></div><div className="risk-main"><div><h2>{Number(alert.probability).toFixed(0)}<small>%</small></h2><p>estimated risk probability</p></div><div className="risk-ring"><span>{alert.riskLevel}</span></div></div><p className="risk-message">{alert.message}</p><button className="dark-button" onClick={() => navigate(`/alerts/${alert._id}`)}>View alert details <ChevronRight size={15} /></button></section> }
function AlertsPage() { const [alerts, setAlerts] = useState([]); useEffect(() => { getAlerts().then(({ alerts: rows }) => setAlerts(rows)).catch(() => {}) }, []); return <><PageTitle eyebrow="MONITORING CENTER" title="Alerts" text="Verified AI-based risk assessments for your area." />{alerts.length ? <div className="alert-list">{alerts.map((alert) => <AlertItem alert={alert} key={alert._id} />)}</div> : <Empty icon={Bell} title="You're all clear" text="No active alerts for your monitored area." />}<button className="text-button" onClick={() => markAllAlertsRead()}>Mark all as read</button></> }
function AlertItem({ alert }) { const navigate = useNavigate(); return <button className="alert-item" onClick={() => navigate(`/alerts/${alert._id}`)} style={{ '--risk': riskColor(alert.riskLevel) }}><span className="alert-dot" /><div><span className="eyebrow">{alert.riskLevel} LANDSLIDE RISK</span><strong>{alert.state}{alert.district ? ` · ${alert.district}` : ''}</strong><p>{alert.message}</p><small>{new Date(alert.createdAt).toLocaleString()}</small></div><ChevronRight /></button> }
function AlertDetail() { const { id } = useParams(); const [alert, setAlert] = useState(null); useEffect(() => { getAlerts().then(({ alerts }) => setAlert(alerts.find((item) => item._id === id))).catch(() => {}) }, [id]); if (!alert) return <Empty icon={Bell} title="Alert unavailable" text="This alert may have expired or is not relevant to your area." />; return <><PageTitle eyebrow="ALERT DETAIL" title={alert.title} text={alert.message} /><div className="detail-risk" style={{ '--risk': riskColor(alert.riskLevel) }}><strong>{alert.riskLevel}</strong><span>{Number(alert.probability).toFixed(2)}% estimated risk</span></div><section className="data-card"><h2>Why are you receiving this alert?</h2><p>Environmental conditions reached the alert threshold. This is an AI-based estimate, not a guaranteed event.</p><div className="data-grid">{Object.entries(alert.data || {}).filter(([key]) => ['rainfall', 'temperature', 'slope', 'elevation', 'terrainAdjustment'].includes(key)).map(([key, value]) => <div key={key}><span>{key.replace(/([A-Z])/g, ' $1')}</span><strong>{value ?? 'Not available'}</strong></div>)}</div></section><div className="notice"><AlertTriangle size={18} /><div><strong>What should you do?</strong><p>Follow local authority instructions, move away from unstable slopes when directed, and call 112 in an emergency.</p></div></div><a className="call-button" href="tel:112"><Phone size={17} /> Call 112</a></> }
function MapPage() { return <><PageTitle eyebrow="REGIONAL VIEW" title="Risk map" text="Verified alerts are shown by state. No alert means no marker is displayed." /><div className="map-placeholder"><div className="map-grid" /><div className="map-silhouette" /><span className="map-label">NORTH-EAST INDIA<br /><small>Live alert markers connect here</small></span></div><div className="map-note"><Info size={17} /><p>Markers come only from alerts received from the application API.</p></div></> }
function SafetyPage() { const [checked, setChecked] = useState(() => JSON.parse(localStorage.getItem('bhu-kit') || '[]')); const toggle = (item) => setChecked((current) => { const next = current.includes(item) ? current.filter((value) => value !== item) : [...current, item]; localStorage.setItem('bhu-kit', JSON.stringify(next)); return next }); return <><PageTitle eyebrow="SAFETY CENTER" title="Know what to do" text="Practical guidance for before, during, and after a landslide." />{safetySections.map((section) => <section className="safety-section" key={section.title}><h2>{section.title}</h2>{section.items.map((item) => <p key={item}><Check size={15} />{item}</p>)}</section>)}<section className="kit-card"><div className="section-heading"><div><span className="eyebrow">PREPAREDNESS</span><h2>Emergency kit</h2></div><span>{checked.length}/{kitItems.length}</span></div>{kitItems.map((item) => <label key={item}><input type="checkbox" checked={checked.includes(item)} onChange={() => toggle(item)} /> <span>{item}</span></label>)}</section><div className="notice"><Info size={18} /><p>Follow instructions from local authorities and emergency services. Bhu Raksha does not replace official warnings.</p></div></> }
function ProfilePage() { const { user, logout } = useAuth(); const navigate = useNavigate(); return <><PageTitle eyebrow="YOUR ACCOUNT" title="Profile" text="Keep your area and safety preferences up to date." /><section className="profile-card"><div className="profile-avatar">{user.name.slice(0, 1)}</div><h2>{user.name}</h2><p>{user.email}</p><span>{user.district}, {user.state}</span></section><div className="profile-links"><NavLink to="/contacts"><User size={18} /> Emergency contacts <ChevronRight /></NavLink><NavLink to="/map"><Map size={18} /> Monitored area <ChevronRight /></NavLink><NavLink to="/safety"><Shield size={18} /> Safety center <ChevronRight /></NavLink></div><button className="logout-button" onClick={async () => { await logout(); navigate('/login') }}>Log out</button></> }
function ContactsPage() { const [contacts, setContacts] = useState([]); const [form, setForm] = useState({ name: '', relationship: '', phone: '' }); const refresh = () => getContacts().then(({ contacts: rows }) => setContacts(rows)).catch(() => {}); useEffect(refresh, []); async function submit(event) { event.preventDefault(); await addContact(form); setForm({ name: '', relationship: '', phone: '' }); refresh() } return <><PageTitle eyebrow="YOUR SUPPORT CIRCLE" title="Emergency contacts" text="Save up to five people you trust. Automatic SMS is not configured." />{contacts.map((contact) => <div className="contact-row" key={contact._id}><div><strong>{contact.name}</strong><span>{contact.relationship}</span></div><a href={`tel:${contact.phone}`}><Phone size={16} /> Call</a><button onClick={async () => { await deleteContact(contact._id); refresh() }}><X size={16} /></button></div>)}<form className="contact-form" onSubmit={submit}><h2>Add a trusted contact</h2><input placeholder="Name" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder="Relationship" value={form.relationship} onChange={(e) => setForm({ ...form, relationship: e.target.value })} /><input placeholder="Phone number" required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><button className="primary-button"><Plus size={17} /> Add contact</button></form></> }
function AuthPage({ mode }) { const isLogin = mode === 'login'; const { login: signIn, signup: createAccount } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', phone: '', password: '', confirmPassword: '', state: 'ASSAM', district: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(event) { event.preventDefault(); setError(''); setLoading(true); try { if (isLogin) await signIn({ email: form.email, password: form.password }); else await createAccount(form); navigate('/') } catch (e) { setError(e.message) } finally { setLoading(false) } } return <div className="auth-page"><div className="auth-brand"><span className="brand-mark"><Mountain size={21} /><Shield size={14} /></span><strong>BHU RAKSHA</strong><small>STAY ALERT. STAY SAFE.</small></div><div className="auth-copy"><span className="eyebrow">CITIZEN SAFETY PLATFORM</span><h1>{isLogin ? 'A calmer way to stay informed.' : 'Build your safety circle.'}</h1><p>Local risk intelligence, practical guidance, and emergency support for North-East India.</p></div><form className="auth-form" onSubmit={submit}>{!isLogin && <><input placeholder="Full name" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input placeholder="Phone number" required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><div className="form-row"><select value={form.state} onChange={(e) => setForm({ ...form, state: e.target.value })}>{['ASSAM', 'ARUNACHAL PRADESH', 'MEGHALAYA', 'MANIPUR', 'MIZORAM', 'NAGALAND', 'SIKKIM', 'TRIPURA'].map((state) => <option key={state}>{state}</option>)}</select><input placeholder="District" required value={form.district} onChange={(e) => setForm({ ...form, district: e.target.value })} /></div></>}<input type="email" placeholder="Email address" required value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input type="password" placeholder="Password" required minLength="8" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} />{!isLogin && <input type="password" placeholder="Confirm password" required value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} />}{error && <div className="auth-error"><AlertTriangle size={15} />{error}</div>}<button className="primary-button" disabled={loading}>{loading ? 'Please wait...' : isLogin ? 'Sign in' : 'Create account'}</button></form><p className="auth-switch">{isLogin ? 'New to Bhu Raksha?' : 'Already have an account?'} <button onClick={() => navigate(isLogin ? '/signup' : '/login')}>{isLogin ? 'Create account' : 'Sign in'}</button></p><small className="auth-disclaimer">AI-based risk estimates are not official emergency warnings.</small></div> }
function SOSButton({ onClick }) { return <button className="sos-button" onClick={onClick}><Siren size={19} /><span>SOS</span></button> }
function SOSModal({ close }) { const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); async function activate() { setLoading(true); try { const location = await getCurrentLocation().catch(() => ({})); await createSOS(location); setMessage('SOS event recorded. Call 112 for emergency services.'); } catch (e) { setMessage(e.message) } finally { setLoading(false) } } return <div className="modal-backdrop"><div className="sos-modal"><button className="modal-close" onClick={close}><X /></button><div className="sos-symbol"><Siren size={25} /></div><h2>Emergency assistance</h2><p>Are you sure you want to activate SOS? This records your request with Bhu Raksha. It does not dispatch responders.</p>{message ? <div className="notice">{message}</div> : <div className="modal-actions"><button onClick={close}>Cancel</button><button className="danger-button" onClick={activate} disabled={loading}>{loading ? 'Activating...' : 'Activate SOS'}</button></div>}<a className="call-button" href="tel:112"><Phone size={16} /> Call 112</a></div></div> }
function PageTitle({ eyebrow, title, text }) { return <div className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div> }
function Empty({ icon: Icon, title, text }) { return <div className="empty"><Icon size={24} /><h2>{title}</h2><p>{text}</p></div> }
function PageLoader({ text }) { return <div className="page-loader"><div className="brand-mark"><Mountain size={21} /></div><p>{text}</p></div> }
export default App
